---
name: CI

on:
  push:
    branches:
    - master
    - v1
  pull_request:
    branches:
    - master
    - v1

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CI: true
    strategy:
      matrix:
        node-version: [18.x, 20.x]
    name: Use Node.js ${{ matrix.node-version }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: yarn install
        run: yarn
      - name: Unittesting
        run: yarn test
      - name: Linting
        run: yarn lint
